create table public.invitado (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  edad bigint not null,
  id_progreso bigint not null,
  constraint invitado_pkey primary key (id),
  constraint invitado_id_key unique (id),
  constraint invitado_id_progreso_fkey foreign KEY (id_progreso) references progreso_invitado (id)
) TABLESPACE pg_default;

create table public.progreso_invitado (
  id bigint generated by default as identity not null,
  racha_1 bigint not null default '0'::bigint,
  racha_2 bigint not null default '0'::bigint,
  nivel bigint not null default '1'::bigint,
  constraint progreso_invitado_pkey primary key (id)
) TABLESPACE pg_default;

create table public.progreso_usuario (
  id bigint generated by default as identity not null,
  racha_1 bigint not null default '0'::bigint,
  racha_2 bigint not null default '0'::bigint,
  nivel bigint not null default '1'::bigint,
  constraint progreso_usuario_pkey primary key (id),
  constraint progreso_usuario_id_key unique (id)
) TABLESPACE pg_default;

create table public.usuario (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  email character varying null,
  edad bigint not null,
  auth_user uuid null,
  id_progreso bigint not null,
  constraint usuario_pkey primary key (id),
  constraint usuario_id_key unique (id),
  constraint usuario_auth_user_fkey foreign KEY (auth_user) references auth.users (id),
  constraint usuario_id_progreso_fkey foreign KEY (id_progreso) references progreso_usuario (id)
) TABLESPACE pg_default;